import { clues, getLocation, locations } from './data';
import type { GameState } from './types';
const SAVE_KEY='free-detective-case-001-v1';
export function initialState():GameState{return{started:false,introRead:false,finished:false,won:false,discoveredLocationIds:locations.filter(l=>l.initial).map(l=>l.id),foundClueIds:[],questionedCharacterIds:[],completedActionIds:[],timelineEventIds:[],notes:'',selectedTab:'case',selectedLocationId:'bennett_home',mapMode:'satellite'}};
export function loadGame(){try{const raw=localStorage.getItem(SAVE_KEY);return raw?JSON.parse(raw) as GameState:null}catch{return null}}
export function saveGame(state:GameState){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state))}catch{}}
export function clearSave(){try{localStorage.removeItem(SAVE_KEY)}catch{}}
export function discoverFromClues(state:GameState){const next={...state,discoveredLocationIds:[...state.discoveredLocationIds]};const found=new Set(next.foundClueIds);const req:Record<string,string[]>={rainier_lab:['clue_photo'],madison_market:['clue_photo'],reed_garage:['clue_van'],city_news:['clue_june_chat'],northline_storage:['clue_manifest']};Object.entries(req).forEach(([loc,ids])=>{if(ids.every(id=>found.has(id))&&!next.discoveredLocationIds.includes(loc))next.discoveredLocationIds.push(loc)});return next}
export function performAction(state:GameState,locationId:string,actionId:string){const loc=getLocation(locationId),a=loc?.actions.find(x=>x.id===actionId);if(!loc||!a)return state;if(a.once&&state.completedActionIds.includes(actionId))return state;if(a.requiresClueIds?.some(id=>!state.foundClueIds.includes(id)))return state;const next={...state,foundClueIds:[...new Set([...state.foundClueIds,...a.clueIds])],completedActionIds:a.once?[...state.completedActionIds,actionId]:state.completedActionIds,questionedCharacterIds:a.characterId&&!state.questionedCharacterIds.includes(a.characterId)?[...state.questionedCharacterIds,a.characterId]:state.questionedCharacterIds};return discoverFromClues(next)}
export function calculateScore(state:GameState,answers:GameState['finalAnswers']){if(!answers)return 0;let score=0;if(answers.person==='leah')score+=35;if(answers.motive==='exposure')score+=25;if(answers.method==='lured')score+=20;if(answers.location==='northline_storage')score+=20;score+=Math.min(10,state.foundClueIds.filter(id=>clues.find(c=>c.id===id)?.importance==='critical').length*1.5);return Math.min(100,Math.round(score))}
