import {useMemo,useState} from 'react';
import {BookOpen,ChevronRight,FileText,MessageSquare,NotebookPen,Search,Users,Clock3,Lock,Check,PanelRightClose,PanelRightOpen,Send,MapPin,Radio,Eye,Camera,FileSearch,CircleAlert} from 'lucide-react';
import MapView from '@/game/MapView';
import {characters,clues,getCharacter,getLocation,locations,timeline,dialogueNodes} from '@/game/data';
import {calculateScore,discoverFromClues,performAction} from '@/game/engine';
import type {DialogueNode,GameState,Tab} from '@/game/types';

const tabs:{id:Tab;label:string;icon:any}[]=[{id:'case',label:'Дело',icon:BookOpen},{id:'people',label:'Люди',icon:Users},{id:'clues',label:'Улики',icon:Search},{id:'notes',label:'Заметки',icon:NotebookPen},{id:'timeline',label:'Хронология',icon:Clock3}];

const actionDialogue:Record<string,string>={home_mother:'home_mother_1',school_daniel:'school_daniel_1',school_june:'school_june_1',lab_nora:'lab_nora_1',market_marcus:'market_marcus_1',garage_camera:'garage_sam_1',news_leah:'news_leah_1'};
const actionIcon:Record<string,any>={home_room:Eye,home_mother:MessageSquare,school_records:FileSearch,school_june:MessageSquare,school_daniel:MessageSquare,lab_archive:Camera,lab_nora:MessageSquare,market_marcus:MessageSquare,market_books:FileSearch,garage_camera:Camera,garage_route:MapPin,news_leah:MessageSquare,storage_access:Radio,storage_section:Eye,storage_records:FileSearch};

export default function GameScreen({state,setState,onFinish,onRestart}:{state:GameState;setState:React.Dispatch<React.SetStateAction<GameState>>;onFinish:(won:boolean)=>void;onRestart:()=>void}){
  const [finalOpen,setFinalOpen]=useState(false);
  const [detailClue,setDetailClue]=useState<string|null>(null);
  const [sidebar,setSidebar]=useState(true);
  const [dialogue,setDialogue]=useState<DialogueNode|null>(null);
  const [eventNotice,setEventNotice]=useState<{title:string;text:string;clues:string[]}|null>(null);
  const [dialogueNodeId,setDialogueNodeId]=useState<string|null>(null);
  const loc=getLocation(state.selectedLocationId||'bennett_home')!;
  const discovered=state.discoveredLocationIds;
  const found=useMemo(()=>clues.filter(c=>state.foundClueIds.includes(c.id)),[state.foundClueIds]);
  const totalClues=clues.length;
  const progress=Math.round(Math.min(100,(found.length/totalClues)*100));

  const select=(id:string)=>setState(s=>({...s,selectedLocationId:id,selectedTab:'case'}));
  const action=(id:string)=>{
    const before=new Set(state.foundClueIds);
    const next=performAction(state,loc.id,id);
    setState(next);
    const added=next.foundClueIds.filter(x=>!before.has(x));
    const dialogueId=actionDialogue[id];
    if(dialogueId){setDialogue(dialogueNodes[dialogueId]);setDialogueNodeId(dialogueId);return;}
    const actionDef=loc.actions.find(a=>a.id===id);
    if(actionDef){
      const clueNames=added.map(x=>clues.find(c=>c.id===x)?.title||'').filter(Boolean);
      setEventNotice({title:actionDef.label,text:actionDef.description,clues:clueNames});
    }
  };
  const setTab=(tab:Tab)=>setState(s=>({...s,selectedTab:tab}));
  const note=(v:string)=>setState(s=>({...s,notes:v}));

  const chooseDialogue=(choice:{id:string;clueIds?:string[];nextId?:string;text?:string;note?:string})=>{
    const nextState=discoverFromClues({...state,foundClueIds:[...new Set([...state.foundClueIds,...(choice.clueIds||[])])],dialogueFlags:[...(state.dialogueFlags||[]),choice.id]});
    setState(nextState);
    if(choice.nextId&&dialogueNodes[choice.nextId]){setDialogue(dialogueNodes[choice.nextId]);setDialogueNodeId(choice.nextId);return}
    const added=(choice.clueIds||[]).map(id=>clues.find(c=>c.id===id)?.title).filter(Boolean) as string[];
    setDialogue(null);setDialogueNodeId(null);
    if(added.length||choice.text){setEventNotice({title:'Разговор записан',text:choice.text||'Показание добавлено в материалы дела.',clues:added});}
  };

  const canFinal=state.foundClueIds.length>=10;
  return <div className="game-shell">
    <header className="game-top"><div className="brand"><span className="brand-mark">OC</span><div><b>OPEN CASES</b><small>Дело №001 · Тишина на Мэдисон</small></div></div><div className="top-status"><span><span className="live-dot"/> СИСТЕМА АКТИВНА</span><span>{found.length} / {totalClues} улик</span><button onClick={onRestart} className="top-link">Сбросить</button></div></header>
    <div className="game-body">
      <aside className={`left-rail ${sidebar?'':'collapsed'}`}>{sidebar&&<><div className="rail-head"><div><span className="eyebrow">РАССЛЕДОВАНИЕ</span><strong>Тишина на Мэдисон</strong></div><button onClick={()=>setSidebar(false)} aria-label="Свернуть панель"><PanelRightClose size={17}/></button></div><nav>{tabs.map(t=>{const Icon=t.icon;return <button key={t.id} className={state.selectedTab===t.id?'active':''} onClick={()=>setTab(t.id)}><Icon size={17}/><span>{t.label}</span>{t.id==='clues'&&found.length>0&&<em>{found.length}</em>}</button>})}</nav><div className="rail-progress"><div><span>Материалы дела</span><b>{progress}%</b></div><div className="progress"><i style={{width:`${progress}%`}}/></div><small>Открыто {discovered.length} из {locations.length} точек</small></div></>}{!sidebar&&<button className="expand-rail" onClick={()=>setSidebar(true)} aria-label="Развернуть панель"><PanelRightOpen size={18}/></button>}</aside>
      <section className="map-panel"><MapView locations={locations} discovered={discovered} selectedId={state.selectedLocationId} mode={state.mapMode} onSelect={select} mapTemplateId="small_town"/><div className="map-toolbar"><button className={state.mapMode==='scheme'?'active':''} onClick={()=>setState(s=>({...s,mapMode:'scheme'}))}>СХЕМА</button><button className={state.mapMode==='satellite'?'active':''} onClick={()=>setState(s=>({...s,mapMode:'satellite'}))}>СПУТНИК</button></div><div className="map-hint"><MapPin size={13}/><span>Выберите точку на карте</span></div><div className="map-legend"><span><i className="legend-dot open"/> открыта</span><span><i className="legend-dot new"/> выбрана</span><span><i className="legend-dot locked"/> неизвестна</span></div><div className="case-stamp">SEATTLE<br/><b>CASE 001</b></div></section>
      <aside className="right-panel"><div className="panel-scroll">{state.selectedTab==='case'&&<CaseTab loc={loc} state={state} action={action} setFinalOpen={setFinalOpen} canFinal={canFinal}/>} {state.selectedTab==='people'&&<PeopleTab state={state} select={select}/>} {state.selectedTab==='clues'&&<CluesTab found={found} onOpen={setDetailClue}/>} {state.selectedTab==='notes'&&<NotesTab value={state.notes} onChange={note}/>} {state.selectedTab==='timeline'&&<TimelineTab state={state}/>}</div></aside>
    </div>
    {detailClue&&<ClueModal clue={clues.find(c=>c.id===detailClue)!} onClose={()=>setDetailClue(null)}/>} 
    {eventNotice&&<EventModal notice={eventNotice} onClose={()=>setEventNotice(null)}/>} 
    {dialogue&&<DialogueModal node={dialogue} state={state} nodeId={dialogueNodeId||''} onChoose={chooseDialogue} onClose={()=>{setDialogue(null);setDialogueNodeId(null)}}/>}
    {finalOpen&&<FinalModal state={state} onClose={()=>setFinalOpen(false)} onSubmit={(answers)=>{const score=calculateScore(state,answers);setState(s=>({...s,finalAnswers:answers,score,finished:true,won:score>=70}));setFinalOpen(false);onFinish(score>=70)}}/>}
  </div>
}

function CaseTab({loc,state,action,setFinalOpen,canFinal}:{loc:any;state:GameState;action:(id:string)=>void;setFinalOpen:(v:boolean)=>void;canFinal:boolean}){const open=state.discoveredLocationIds.includes(loc.id);return <><div className="panel-title selected-location-heading"><span className="eyebrow"><MapPin size={12}/> ВЫБРАННАЯ ТОЧКА</span><h2>{loc.title}</h2><p>{loc.address}</p></div><div className="location-hero"><img src={loc.image}/><span>{loc.category}</span><div className="hero-badge">{open?'ДОСТУПНО':'НЕ ИССЛЕДОВАНО'}</div></div><div className="panel-copy"><p>{loc.description}</p></div>{!open?<div className="locked-card"><Lock size={18}/><b>Локация пока закрыта</b><span>{loc.lockedReason}</span></div>:<div className="actions"><span className="section-label">Доступные действия</span>{loc.actions.map((a:any)=>{const done=state.completedActionIds.includes(a.id),blocked=a.requiresClueIds?.some((id:string)=>!state.foundClueIds.includes(id));const Icon=actionIcon[a.id]||Search;return <button key={a.id} disabled={done||blocked} onClick={()=>action(a.id)} className="action-card"><div className="action-icon">{done?<Check size={17}/>:<Icon size={17}/>}</div><div><b>{a.label}</b><span>{done?'Завершено':blocked?'Сначала найдите нужную зацепку.':a.description}</span></div><ChevronRight size={17}/></button>})}</div>}<div className="location-people">{loc.characterIds.length>0&&<><span className="section-label">Персонажи в точке</span>{loc.characterIds.map((id:string)=>{const c=getCharacter(id)!;return <div className="mini-person" key={id}><img src={c.portrait}/><div><b>{c.name}</b><span>{c.relation}</span></div></div>})}</>}</div><button className={`final-btn ${canFinal?'ready':''}`} disabled={!canFinal} onClick={()=>setFinalOpen(true)}><FileText size={18}/>{canFinal?'Сформировать версию расследования':'Соберите минимум 10 улик'}</button></>}
function PeopleTab({state,select}:{state:GameState;select:(id:string)=>void}){return <><div className="panel-title"><span className="eyebrow">ДОСЬЕ</span><h2>Люди</h2><p>{characters.length} фигур в деле</p></div><div className="people-list">{characters.map(c=><button key={c.id} className="person-card" onClick={()=>c.locationId&&select(c.locationId)}><img src={c.portrait}/><div><b>{c.name}</b><span>{c.age} · {c.role}</span><small>{state.questionedCharacterIds.includes(c.id)?'Опрошен':'Не опрошен'}</small></div><ChevronRight size={16}/></button>)}</div></>}
function CluesTab({found,onOpen}:{found:any[];onOpen:(id:string)=>void}){return <><div className="panel-title"><span className="eyebrow">ДОКАЗАТЕЛЬСТВА</span><h2>Улики <em>{found.length}</em></h2><p>Нажимайте на материалы и сопоставляйте детали.</p></div><div className="clue-list">{found.map(c=><button className={`clue-card ${c.importance}`} key={c.id} onClick={()=>onOpen(c.id)}><div className="clue-type">{c.type}</div><b>{c.title}</b><span>{c.description}</span><small>{c.foundWhen}</small></button>)}{found.length===0&&<div className="empty">Пока ничего. Начните с дома Беннеттов и школы.</div>}</div></>}
function NotesTab({value,onChange}:{value:string;onChange:(v:string)=>void}){return <><div className="panel-title"><span className="eyebrow">РАБОЧИЙ БЛОКНОТ</span><h2>Заметки</h2><p>Пишите собственные версии. Игра не проверяет текст заметок.</p></div><textarea className="notes" value={value} onChange={e=>onChange(e.target.value)} placeholder={'Например:\n20:07 — Майя официально покинула школу.\n20:19 — фургон у мастерской.\nПочему Дэниел говорит 20:14?'} /><div className="note-tip"><NotebookPen size={16}/><span>Хорошая привычка: рядом с каждой гипотезой записывайте, какая улика её подтверждает.</span></div></>}
function TimelineTab({state}:{state:GameState}){const events=timeline.filter(t=>!t.id||state.timelineEventIds.length===0||state.timelineEventIds.includes(t.id)||['t1','t2','t3'].includes(t.id));return <><div className="panel-title"><span className="eyebrow">ВРЕМЕННАЯ ЛИНИЯ</span><h2>Хронология</h2><p>Факты, подтверждённые в ходе расследования.</p></div><div className="timeline">{events.map(t=><div className="timeline-row" key={t.id}><time>{t.time}</time><div><b>{t.title}</b><span>{t.text}</span><small>{t.source}</small></div></div>)}</div></>}
function ClueModal({clue,onClose}:{clue:any;onClose:()=>void}){return <div className="modal-backdrop" onClick={onClose}><div className="modal clue-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">{clue.type} · {clue.importance==='critical'?'КЛЮЧЕВАЯ':clue.importance==='important'?'ВАЖНАЯ':'КОНТЕКСТ'}</span><h2>{clue.title}</h2></div><button onClick={onClose}>×</button></div><p>{clue.description}</p><div className="evidence-detail"><MessageSquare size={18}/><span>{clue.detail}</span></div><div className="related"><b>Связи</b><span>{clue.relatedClues.length} связанных улик · {clue.relatedCharacters.length} персонажей</span></div></div></div>}
function EventModal({notice,onClose}:{notice:{title:string;text:string;clues:string[]};onClose:()=>void}){return <div className="event-layer"><div className="event-card"><div className="event-accent"/><div className="event-kicker"><CircleAlert size={14}/> ОПЕРАТИВНАЯ ЗАПИСЬ</div><h3>{notice.title}</h3><p>{notice.text}</p>{notice.clues.length>0&&<div className="event-discoveries"><span>Добавлено в дело</span>{notice.clues.map(c=><b key={c}>+ {c}</b>)}</div>}<button className="btn primary full" onClick={onClose}>Продолжить</button></div></div>}
function DialogueModal({node,onClose,onChoose}:{node:DialogueNode;state:GameState;nodeId:string;onChoose:(c:any)=>void}){const character=getCharacter(node.characterId)!;return <div className="modal-backdrop dialogue-backdrop"><div className="modal dialogue-modal" onClick={e=>e.stopPropagation()}><div className="dialogue-top"><div><span className="eyebrow">{node.eyebrow}</span><h2>{node.title}</h2></div><button onClick={onClose}>×</button></div><div className="speaker"><img src={character.portrait}/><div><b>{character.name}</b><span>{character.role}</span></div></div><div className="dialogue-lines">{node.lines.map((line,i)=><p key={i}>{line}</p>)}</div><div className="choice-list"><span className="section-label">Что спросить дальше</span>{node.choices.map(c=><button className="dialogue-choice" key={c.id} onClick={()=>onChoose(c)}><div><b>{c.label}</b><span>{c.text||'Продолжить разговор и проверить показания.'}</span></div><ChevronRight size={17}/></button>)}</div><div className="dialogue-foot">{node.intro}</div></div></div>}
function FinalModal({state,onClose,onSubmit}:{state:GameState;onClose:()=>void;onSubmit:(a:any)=>void}){const [person,setPerson]=useState('');const [motive,setMotive]=useState('');const [method,setMethod]=useState('');const [location,setLocation]=useState('');return <div className="modal-backdrop"><div className="modal final-modal"><div className="modal-head"><div><span className="eyebrow">ФИНАЛЬНАЯ ВЕРСИЯ</span><h2>Что произошло?</h2></div><button onClick={onClose}>×</button></div><p>Сформируйте свою версию только из того, что удалось подтвердить. Ошибка не закрывает дело автоматически.</p><Select label="Кто организовал исчезновение?" value={person} set={setPerson} opts={[['leah','Лия Моррис'],['daniel','Дэниел Кроу'],['nora','Нора Вэйл'],['sam','Сэмюэл Рид']]}/><Select label="Какой был мотив?" value={motive} set={setMotive} opts={[['exposure','Скрыть схему подмены серийных номеров'],['money','Получить выкуп'],['revenge','Личная месть'],['escape','Помочь Майе скрыться']]}/><Select label="Как Майю заманили?" value={method} set={setMethod} opts={[['lured','Сообщением о встрече и фотографиях'],['force','Сразу силой у школы'],['fake','Поддельным звонком от матери'],['random','Случайно возле магазина']]}/><Select label="Где ключевая точка?" value={location} set={setLocation} opts={[['northline_storage','Northline Storage'],['lincoln_school','Lincoln High School'],['reed_garage','Reed Auto'],['city_news','Seattle Ledger']]}/><button className="btn primary full" disabled={!person||!motive||!method||!location} onClick={()=>onSubmit({person,motive,method,location})}>Закрыть дело <Send size={17}/></button></div></div>}
function Select({label,value,set,opts}:{label:string;value:string;set:(v:string)=>void;opts:string[][]}){return <label className="select-wrap"><span>{label}</span><select value={value} onChange={e=>set(e.target.value)}><option value="">Выберите ответ…</option>{opts.map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label>}
